baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Kobuki's Blog"
theme = "ananke"

[pagination]
  pagerSize = 5  # 1ページあたりの記事数

# サマリーの長さを設定（単語数）
summaryLength = 30

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  mainSections = ["posts"]  # 投稿があるディレクトリ名
  recent_posts_number = 5   # 表示する投稿数（デフォルトは3）
  custom_css = ["css/custom.css"]  # カスタムCSSファイルを指定

[params.ananke]
  show_recent_posts = true  # 最近の投稿を表示

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # HTMLタグを許可する設定

# 404ページの設定
[permalinks]
  posts = "/posts/:year/:month/:day/:slug/"

# カスタムヘッダーの設定
[headers]
  for = "/css/*"
    [headers.values]
    Content-Type = "text/css"

[[menu.main]]
  identifier = "home"
  name = "直近の投稿"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "posts"
  name = "記事一覧"
  url = "/posts/"
  weight = 2

[[menu.main]]
  identifier = "about"
  name = "プロフィール"
  url = "/about/"
  weight = 3
