baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Kobuki's Blog"
theme = "ananke"

# サマリーの長さを設定（単語数）
summaryLength = 30

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  mainSections = ["posts"]  # 投稿があるディレクトリ名
  recent_posts_number = 5   # 表示する投稿数（デフォルトは3）

[params.ananke]
  show_recent_posts = true  # 最近の投稿を表示
